apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "app-chart.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "app-chart.labels" . | nindent 4 }}
data:
  index.html: |
    {{- tpl ($.Files.Get .Values.configmap.htmlPath) . | nindent 4 }}
  default.conf: |
    {{- tpl ($.Files.Get .Values.configmap.confPath) . | nindent 4 }}