apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "app-chart.fullname" . }}
  annotations:
    kubernetes.io/ingress.class: {{ .Values.ingress.ingressClassName }}
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  ingressClassName: {{ .Values.ingress.ingressClassName }}
  rules:
    - host: {{ .Values.ingress.host }}
      http:
        paths:
          - pathType: Prefix
            path: "/"
            backend:
              service:
                name: {{ include "app-chart.fullname" . }}
                port:
                  number: {{ .Values.service.port }}